### ISSUE TITLE
"make install" only copies the folder, doesn't build

### ISSUE THREAD

**Issue by JetLennit** [clieg/coffeetch#4]
In the Makefile, if you use make install it only copies the file without building. This makes the user have to run "make" and then "make install"

`sudo cp coffeetch /usr/bin`
`cp: cannot stat 'coffeetch': No such file or directory`
`make: *** [Makefile:13: install] Error 1`

**Comment by JetLennit** [comment]
#[https://github.com/JetLennit/coffeetch](url) I went ahead and modified the readme to reflect this (and added an option for arch) in a fork found at that link

**Comment by JetLennit** [comment]
I'll close this now

**Comment by clieg** [comment]
Hello, I've fixed the problem with the Makefile, this should build the coffeetch now. I also added the installation guide for Arch Linux. :)
